---
- name: BIG-IQ and DO Lab - Create VE
  hosts: "{{ env }}"
  vars_files:
    - inventory/group_vars/{{ env }}.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq_<user>.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','{{ user }}') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: Create VE
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/cm/cloud/tasks/create-ve
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          veName: "{{ vename }}"
          description: "VE creation"
          cloudEnvironmentReference:
            link: https://localhost/mgmt/cm/cloud/environments/{{ cloudEnvironmentReference }}
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check VE Creation Task
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/cm/cloud/tasks/create-ve/{{json_response.json.instanceId}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check VE Creation Task
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/cm/cloud/tasks/create-ve/{{json_response.json.instanceId}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json[0].results[0].state != 'FINISHED'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json