---
- hosts: f5_bigiq_cm
  connection: local
  serial: 1
  gather_facts: false
  vars:
    provider:
      server: "{{ hostvars[groups['f5_bigiq_cm'][0]]['ansible_host'] }}"
      server_port: 443
      user: admin
      password: "{{ hostvars[groups['f5_bigiq_cm'][0]]['ansible_ssh_pass'] }}"
      auth_provider: "tmos"
      validate_certs: false
    servers: 
      - "10.1.20.126"

  tasks:
    - name: Create a VE in AWS
      include_role:
        name: ansible-role-bigiq_create_ve
      vars:
        cloud_environment: "AWS Roman"
        ve_name: bigipvm-aws-test
      register: status

    - name: Get AWS BIG-IP VE IP address (port 8443)
      debug:
        msg: "{{ ve_ip_Address }}"

    - name: Get AWS BIG-IP VE private Key Filename
      debug:
        msg: "{{ private_key_filename }}"

    - name: Onboard BIG-IP VE with DO
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_service: Device
        atc_method: POST
        atc_declaration: |
          {
            "class": "DO",
            "declaration": {
                "schemaVersion": "1.5.0",
                "class": "Device",
                "async": true,
                "Common": {
                      "class": "Tenant",
                      "myDbVariables": {
                        "class": "DbVariables",
                        "configsync.allowmanagement": "enable"
                      },
                      "myLicense": {
                        "class": "License",
                        "licenseType": "licensePool",
                        "licensePool": "byol-pool",
                        "bigIpUsername": "admin",
                        "bigIpPassword": "u7BnD@4f5"
                      },
                      "myProvision": {
                        "class": "Provision",
                        "ltm": "nominal",
                        "asm": "nominal",
                        "avr": "nominal"
                      },
                      "myNtp": {
                        "class": "NTP",
                        "servers": [
                            "169.254.169.123"
                        ],
                        "timezone": "UTC"
                      },
                      "admin": {
                        "class": "User",
                        "keys": [],
                        "userType": "regular",
                        "partitionAccess": {
                            "all-partitions": {
                                  "role": "admin"
                            }
                        },
                        "password": "u7BnD@4f5"
                      }
                }
            },
            "targetUsername": "admin",
            "targetHost": "{{ ve_ip_Address }}",
            "targetSshKey": {
                "path": "{{ private_key_filename }}"
            },
            "bigIqSettings": {
                "clusterName": "cluster-aws-lab",
                "conflictPolicy": "USE_BIGIQ",
                "deviceConflictPolicy": "USE_BIGIP",
                "failImportOnConflict": false,
                "versionedConflictPolicy": "KEEP_VERSION",
                "statsConfig": {
                  "enabled": true
              }
            }
          }
        atc_delay: 30
        atc_retries: 60
      register: atc_DO_status

#    - debug: var=atc_DO_status

    - name: Deploy AS3 application services to BIG-IP
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_service: AS3
        atc_method: POST
        atc_declaration: |
            {
                "class": "ADC",
                "schemaVersion": "3.12.0",
                "target": {
                    "address": "{{ ve_ip_Address }}"
                },
                "aws": {
                    "class": "Tenant",
                    "webAppServiceHttp2": {
                        "class": "Application",
                        "schemaOverlay": "AS3-F5-HTTP-lb-template-big-iq-default-v1",
                        "template": "http",
                        "serviceMain": {
                            "pool": "Pool",
                            "enable": true,
                            "profileHTTP": {
                                "use": "HTTP_Profile"
                            },
                            "virtualPort": 8080,
                            "profileAnalytics": {
                                "use": "Analytics_Profile"
                            },
                            "virtualAddresses": [
                                "0.0.0.0"
                            ],
                            "class": "Service_HTTP"
                        },
                        "Pool": {
                            "members": [
                                {
                                    "adminState": "enable",
                                    "servicePort": 80,
                                    "serverAddresses": {{ servers }}
                                }
                            ],
                            "class": "Pool"
                        },
                        "HTTP_Profile": {
                            "fallbackRedirect": "https://www.example.com/404",
                            "fallbackStatusCodes": [
                                404
                            ],
                            "class": "HTTP_Profile"
                        },
                        "Analytics_Profile": {
                            "collectIp": true,
                            "collectGeo": true,
                            "collectUrl": true,
                            "collectMethod": true,
                            "collectUserAgent": true,
                            "collectOsAndBrowser": true,
                            "collectResponseCode": true,
                            "collectClientSideStatistics": true,
                            "class": "Analytics_Profile"
                        }
                    }
                }
            }
        atc_delay: 15
        atc_retries: 30
      register: atc_AS3_status

#    - debug: var=atc_AS3_status

    - name: Move an AS3 application service in BIG-IQ dashboard.
      include_role:
        name: f5devcentral.bigiq_move_app_dashboard
      vars:
          apps: 
          - name: myWebApp
            pins:
              - name: aws_webAppServiceHttp2
      register: status
