---
- name: Create Global App on BIG-IQ with site16, 18 and DNS app
  hosts: all
  connection: local

  tasks:
    - name: Move an AS3 application service in BIG-IQ dashboard.
      include_role:
        name: f5devcentral.bigiq_move_app_dashboard
      vars:
          apps: 
          - name: airport_security
            pins:
              - name: security_site16_boston
              - name: security_site18_seattle
              - name: security_fqdn
      register: status
