---
- name: BIG-IQ and AS3 Lab - Example Demo App - TCP Application Service # finance_apps
  hosts: all
  connection: local

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login
      uri:
        url: https://10.1.1.4/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','auth_bigiq_paula.json') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: HTTP Application Service - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://10.1.1.4/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
        class: AS3
        action: deploy
        declaration:
          class: ADC
          schemaVersion: 3.16.0
          target:
            address: 10.1.1.7
          backend:
            class: Tenant
            site20tcp:
              class: Application
              schemaOverlay: AS3-F5-FastL4-TCP-lb-template-default-v2
              template: l4
              serviceMain:
                pool: Pool
                enable: true
                profileL4:
                  use: L4_Profile
                virtualPort: 80
                virtualAddresses:
                - 10.1.10.120
                profileAnalyticsTcp:
                  use: Analytics_TCP_Profile
                class: Service_L4
              Pool:
                members:
                - adminState: enable
                  servicePort: 8080
                  serverAddresses:
                  - 10.1.20.116
                - serverAddresses:
                  - 10.1.20.116
                  servicePort: 8080
                class: Pool
              L4_Profile:
                tcpCloseTimeout: 5
                tcpHandshakeTimeout: 5
                class: L4_Profile
              Analytics_TCP_Profile:
                collectCity: true
                collectRegion: true
                collectCountry: true
                collectPostCode: true
                collectContinent: true
                collectedByClientSide: true
                collectedByServerSide: true
                class: Analytics_TCP_Profile
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://10.1.1.4/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://10.1.1.4/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json.results[0].message != 'in progress'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json