---
- name: BIG-IQ and AS3 Lab - Task 4 - Generic Services
  hosts: "{{ env }}"
  vars_files:
    - inventory/group_vars/{{ env }}.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq_<user>.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','{{ user }}') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth
      
    - name: Validate AS3 Rest Worker is ready
      uri:
        url: "https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/declare"
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        validate_certs: false
      retries: 30
      delay: 5
      register: result
      until: "(result is success) and (result.status == 200)"

    - name: Task 4 - Generic Services - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          class: AS3
          action: deploy
          persist: true
          declaration:
            class: ADC
            schemaVersion: "{{ as3_schemaVersion }}"
            id: isc-lab
            label: Task4
            remark: Task 4 - Generic Services
            target:
              address: "{{ bigip_target_ip }}"
            Task4:
              class: Tenant
              MyWebApp4generic:
                class: Application
                template: generic
                statsProfile:
                  class: Analytics_Profile
                  collectClientSideStatistics: true
                  collectOsAndBrowser: false
                  collectMethod: false
                myServiceTCP:
                  class: Service_Generic
                  virtualAddresses:
                  - "{{ task4_vs }}"
                  virtualPort: 8080
                  pool: web_pool
                  profileAnalytics:
                    use: statsProfile
                web_pool:
                  class: Pool
                  monitors:
                  - tcp
                  members:
                  - servicePort: 80
                    serverAddresses:
                    - "{{ task4_node1 }}"
                    - "{{ task4_node2 }}"
                    shareNodes: true
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

    - pause:
        seconds: 15

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json.results[0].message != 'in progress'"
      retries: 20
      delay: 10

    - debug:
        var: json_response_task.json